THEMES = {
    "Light": {
        "bg": "#FFFFFF",
        "fg": "#1D1D1F",
        "sidebar": "#F5F5F7",
        "panel": "#FFFFFF",
        "border": "#D2D2D7",
        "accent": "#007AFF",
        "accent_hover": "#0051D5",
        "danger": "#FF3B30",
        "text_sec": "#86868B",
        "input_bg": "#F5F5F7",
        "list_bg": "#FAFAFA",
    },
    "Dark": {
        "bg": "#000000",
        "fg": "#F5F5F7",
        "sidebar": "#1C1C1E",
        "panel": "#1C1C1E",
        "border": "#38383A",
        "accent": "#0A84FF",
        "accent_hover": "#409CFF",
        "danger": "#FF453A",
        "text_sec": "#98989D",
        "input_bg": "#2C2C2E",
        "list_bg": "#1C1C1E",
    },
    "Graphite": {
        "bg": "#F2F2F7",
        "fg": "#1D1D1F",
        "sidebar": "#E5E5EA",
        "panel": "#FFFFFF",
        "border": "#C7C7CC",
        "accent": "#8E8E93",
        "accent_hover": "#636366",
        "danger": "#FF3B30",
        "text_sec": "#8E8E93",
        "input_bg": "#E5E5EA",
        "list_bg": "#F9F9FB",
    }
}
